### ISSUE TITLE
re again WssClient::start causes on_error

### ISSUE THREAD

**Issue by brant-m** [eidheim/Simple-WebSocket-Server#102]
WssClient::start and later network error, on_error enters and WssClient::start executes again, on_open comes in.
When you send a message, on_error occurs, and again when WssClient::start, it goes on_open. When you send a message, on_error occurs again.

**Comment by eidheim** [comment]
What server are you communicating with? A minimalistic example would also help. Also keep in mind that the connection is closed if an error occurs (on_error is called).

**Comment by brant-m** [comment]
The internal wss.
If you send a message with disconnected, on_error occurs and you are calling start again to connect to the server.
What if I do not have this plan?

**Comment by brant-m** [comment]
/* header file */
WssClient* _pClient = NULL;
shared_ptr<WssClient::Connection> _connection;

/* cpp file */
void CWSTest::on_message(shared_ptr<WssClient::Connection> connection, shared_ptr<WssClient::Message> message) {  
}

void CWSTest::on_open(shared_ptr<WssClient::Connection> connection) {
  _connection = connection;
}

void CWSTest::on_close(shared_ptr<WssClient::Connection> connection, int status, const string & reason) {
}

void CWSTest::on_error(shared_ptr<WssClient::Connection> connection, const SimpleWeb::error_code &ec) {
}

unsigned WINAPI StartThreadFunction(void* arg) {
  WssClient* pClient = static_cast<WssClient*>(arg);
  while (true)
  {
    pClient->start();
    Sleep(1000);
  }
}

bool CWSTest::Connect() {
  _pClient = new WssClient("localhost:8080/echo", false);
  _pClient->on_message = (std::bind(&CWSTest::on_message, this, std::placeholders::_1, std::placeholders::_2));
  _pClient->on_open = (std::bind(&CWSTest::on_open, this, std::placeholders::_1));
  _pClient->on_close = (std::bind(&CWSTest::on_close, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));
  _pClient->on_error = (std::bind(&CWSTest::on_error, this, std::placeholders::_1, std::placeholders::_2));

  _beginthreadex(&sa, 0, StartThreadFunction, _pClient, 0, NULL);
}

void CWSTest::send_data() {
  auto send_stream = make_shared<WssClient::SendStream>();
  *send_stream << "test";
  _connection->send(send_stream);
}

==============================================

In the above example, in the normal state, when the send_data is called, it is called as on_message, but when the network is disconnected, when the send_data is called from the outside, on_error is generated. If send_data is called again in the above state, on_error is not generated but on_message.

**Comment by brant-m** [comment]
Because of the ambiguous content modify comment

**Comment by eidheim** [comment]
I failed to reproduce your error with the following changes:
```diff
diff --git a/ws_examples.cpp b/ws_examples.cpp
index d2dcfc2..315b31b 100644
--- a/ws_examples.cpp
+++ b/ws_examples.cpp
@@ -137,5 +137,11 @@ int main() {
 
   client.start();
 
+  thread t([&client] {
+    this_thread::sleep_for(chrono::seconds(3));
+    client.stop();
+    client.start();
+  });
+
   server_thread.join();
 }
```

Maybe try call `::stop()` before calling `::start()`? This will close the connection properly maybe.

**Comment by brant-m** [comment]
If you reconnect and send a message, an error occurs in the function below.

void read_message(const std::shared_ptr<Connection> &connection, std::size_t num_additional_bytes) {
      asio::async_read(*connection->socket, connection->message->streambuf, asio::transfer_exactly(num_additional_bytes > 2 ? 0 : 2 - num_additional_bytes), [this, connection](const error_code &ec, std::size_t bytes_transferred) {
        auto lock = connection->handler_runner->continue_lock();
        if(!lock)
          return;
        **if(!ec) { // ec.m_val = 2**
          if(bytes_transferred == 0 && connection->message->streambuf.size() == 0) { // TODO: This might happen on server at least, might also happen here
            this->read_message(connection, 0);
            return;
          }

**Comment by brant-m** [comment]
It is expected to be an internal problem.
Thank you for your reply.

**Comment by eidheim** [comment]
Did you try calling stop before calling start again? Another option is to create a new client object when reconnecting. 

This might also be a Windows issue only, since I have not yet been able to reproduce it on a Unix-like system.

**Comment by brant-m** [comment]
It has been determined that an error will occur if an internal server does not send a reconnected message.
Thank you for answering the wrong question.

**Comment by eidheim** [comment]
I can't reproduce the problem you describe on Unix-like systems. As I see it, this is either a Windows issue or a problem on your side. Without working example code I cannot know.
