### ISSUE TITLE
v1.2 not working anymore

### ISSUE THREAD

**Issue by pp23** [eidheim/Simple-WebSocket-Server#20]
Hi, 

today I have updated my version to v1.2.1. Compilation was still successful, but it did not work anymore. There was no crash, but no endpoint can be created while the ws-server is running. I have a program adding new endpoints to the server when a specific message was sent. So I could send this message, and it seems to create an endpoitn like "^test/[a-zA-Z0-9]+/?$" waiting for new endpoint connections to create, but it didn't create any new endpoints since version 1.2 for example when the client wants to connect to "test/ep1". Also, I cannot see Boost::Log messages on the console anymore. Do you know why?

**Comment by eidheim** [comment]
If I understand it correctly, version 1.2 works for you, but 1.2.1 does not?

v1.2.1 uses boost::thread, but they should be compatible with std::thread.

Also, what platform do you run it on? And your boost version?

**Comment by pp23** [comment]
Sorry, v1.1.2 works, v1.2 and v1.2.1 do not. I use Boost 1.59 on a Linux x86_64 system.

**Comment by eidheim** [comment]
You now have to create the endpoints before you run `server.start()`. This was done to optimise the handling of the requests, that is use precompiled regular expressions. I tested the regular compressions on Debian testing, and this works (based on the latest ws_examples.cpp:
```c++
//Example 2: Echo thrice
//  Sending received messages to three times to connected client
//  Test with the following JavaScript on more than one browser windows:
//    var ws=new WebSocket("ws://localhost:8080/echo_thrice");
//    ws.onmessage=function(evt){console.log(evt.data);};
//    ws.send("test");
auto& echo_thrice=server.endpoint["^/echo_thrice/([a-zA-Z0-9]+)/?$"];
echo_thrice.onmessage=[&server](shared_ptr<WsServer::Connection> connection, shared_ptr<WsServer::Message> message) {
    auto message_str=message->string();
    cout << connection->path_match[1].str() << endl;
    
    auto send_stream1=make_shared<WsServer::SendStream>();
    *send_stream1 << message_str;
    //server.send is an asynchronous function
    server.send(connection, send_stream1, [&server, connection, message_str](const boost::system::error_code& ec) {
        if(!ec) {
            auto send_stream3=make_shared<WsServer::SendStream>();
            *send_stream3 << message_str;
            server.send(connection, send_stream3); //Sent after send_stream1 is sent, and most likely after send_stream2
        }
    });
    //Do not reuse send_stream1 here as it most likely is not sent yet
    auto send_stream2=make_shared<WsServer::SendStream>();
    *send_stream2 << message_str;
    server.send(connection, send_stream2); //Most likely queued, and sent after send_stream1
};

echo_thrice.onopen=[](shared_ptr<WsServer::Connection> connection) {
    cout << connection->path_match[1].str() << endl;
};
```

**Comment by eidheim** [comment]
Sorry for using the more complex example 2 instead of example 1.

**Comment by pp23** [comment]
Ok, is there a way to add enpoints after the server was started?

**Comment by eidheim** [comment]
I think you can do without that using an appropriate regular expression, if not I have to add a function to repopulate opt_endpoint at https://github.com/eidheim/Simple-WebSocket-Server/blob/master/server_ws.hpp#L159. I prefer option 1, to keep things clean.

**Comment by eidheim** [comment]
Also, keep in mind that there has never been a mutex lock on endpoint, so altering it on runtime, might lead to strange behaviour.

**Comment by pp23** [comment]
Ok, I think option 1 will be fine. Thank you for your help :-)

**Comment by eidheim** [comment]
Great, happy to help:)
