### ISSUE TITLE
how to make server_send() synchronous

### ISSUE THREAD

**Issue by alanywlee** [eidheim/Simple-WebSocket-Server#24]
So sorry I don't quite understand your instruction of issue #23. If you mean sleep_for() cause the delay problem, however, I marked the sleep_for() didn't solve the delay problem.

I read the comment in 
https://github.com/eidheim/Simple-WebSocket-Server/blob/master/ws_examples.cpp#L79

I believe it mean server.send() command doesn't send immediately. Even more, if I used a 
for loop to send binary as a series of chunk, just like shown in #23, seems very probably 
arrived not as the same order as I send them out.

Is there any flag or any other way to send binary chunk immediately and synchronous in order?

**Comment by eidheim** [comment]
Consider this simpler example, send_stream1 and send_stream2 are here sent synchronously:
```c++
//Example 2: Echo twice
    //  Sending received messages two times to connected client
    //  Test with the following JavaScript:
    //    var ws=new WebSocket("ws://localhost:8080/echo_twice");
    //    ws.onmessage=function(evt){console.log(evt.data);};
    //    ws.send("test");
    auto& echo_twice=server.endpoint["^/echo_twice/?$"];
    echo_thrice.onmessage=[&server](shared_ptr<WsServer::Connection> connection, shared_ptr<WsServer::Message> message) {
        auto message_str=message->string();
        
        auto send_stream1=make_shared<WsServer::SendStream>();
        *send_stream1 << message_str;
        //server.send is an asynchronous function
        server.send(connection, send_stream1, [&server, connection, message_str](const boost::system::error_code& ec) {
            //send_stream1 is now sent
            if(!ec) {
                auto send_stream2=make_shared<WsServer::SendStream>();
                *send_stream2 << message_str;
                server.send(connection, send_stream2); //send_stream2 is now sent and we know that the client has received send_stream1
            }
        });
    };
```

**Comment by eidheim** [comment]
I would think, however, that creating some kind of synchronisation between the server and client would be a good idea. For instance:
Client: send me some data (for instance frame 0-4)
Server: here is data
Client: thank you, I need some more data now (for instance frame 5-9)
Server: here is some more data
Client: thank you, I need some more data now (for instance frame 10-14)
Server: here is some more data
and so on

Especially when creating a stream application, since you might want the client to buffer some of the stream, but only up to a point, and this would depend on data transferred and data shown on the client.

**Comment by alanywlee** [comment]
Thanks for your instruction about synchronous data transfer. I doubt the delay I encountered is probably there are some limitation on size of binary data to send synchronously. Regarding to the simple modification shown in #23, I encountered more than 5 seconds delay even if I send whole binary file in one chunk.

**Comment by eidheim** [comment]
I saw now in #23 that you are using several client.send(send_stream, nullptr, 130);, that is with the same send_stream. This will lead to unexpected results, and is most likely causing the strange delay. Try to do  client.send(send_stream, nullptr, 130); only once. 

A new SendStream object needs to be created when doing server.send if one does not know if a previous server.send using a SendStream object has completed.

**Comment by alanywlee** [comment]
Regarding to your instruction to send synchronous, it seems not able to send fix size (e.g., 80 pixels per chunk) of binary chunks using a for loop. Hard code 10 -  20 server.send(){}  by hand seems a little bit wired.

**Comment by eidheim** [comment]
Avoid for loops when working with an asynchronous protocol like websocket. If you need to send several messages in one event, you need to implement it as a recursive function. Also you need to make sure your file stays open and is accessible in the callback (send_message2). I suggest though that you implement it as the Client-Message example I wrote in my second-last post. That is, with one server.send for each onmessage for instance. I think this would be simplest.
