### ISSUE TITLE
server crashes with *** Error in `./ws_examples': double free or corruption (out): 0x00007f0014003160 ***

### ISSUE THREAD

**Issue by superlambchops** [eidheim/Simple-WebSocket-Server#26]
ws_example crashes with:
*** Error in `./ws_examples': double free or corruption (out): 0x################ ***
when using ng-websocket in an angularjs page. It occurs using chromium when I exit or close the associated browser tab. It doesn't happen using firefox or if I navigate away leaving the tab open.

**Comment by eidheim** [comment]
What platform are you on? And would you mind posting a backtrace (add compile option -g in the CMakeLists.txt)?

**Comment by superlambchops** [comment]
I'm on linux (Ubuntu 15.04)
It is only caused when chromium is run on the same machine.
[gdb_backtrace.txt](https://github.com/eidheim/Simple-WebSocket-Server/files/77966/gdb_backtrace.txt)

**Comment by eidheim** [comment]
Thank you, will have a look at it later Today or Tomorrow. Are you using g++4.8, or g++4.9 (or later)?

**Comment by eidheim** [comment]
And what boost version are you running? Still looking for the problem, at the moment I'm thinking it might be a coroutine issue (maybe from using an older boost version), but I'll look into it further. I am also unable to reproduce the issue (have not tried ng-websocket though).

**Comment by eidheim** [comment]
Very strange that the commit solved the issue. Do you see why?

**Comment by superlambchops** [comment]
sorry no to get back earler: g++4.9 and boost1.55 if it still matters.
Does send_queue.clear() act like a flush and try to write something to an endpoint that is already gone where erase just deletes it without any other actions?

**Comment by eidheim** [comment]
Does it still crash with ng-websocket by the way?

**Comment by eidheim** [comment]
And please try the latest commit.

**Comment by superlambchops** [comment]
Looks good. I can no longer make it crash.
