### ISSUE TITLE
Compilation Issue with Windows Visual Studio 2012

### ISSUE THREAD

**Issue by serkomen** [eidheim/Simple-WebSocket-Server#29]
Hi there,

On Windows machine, we added the header files to our Visual Studio c++ project. Yet, we cannot get it compiled since it does not have support for c++11. Do you have any solution for it?

Regards,

**Comment by eidheim** [comment]
Sorry, c++11 is required for for instance shared_ptr and lambdas. It would require a lot of work to support pre c++11 compilers.
