### ISSUE TITLE
How to test the simple-websocket-server with the client

### ISSUE THREAD

**Issue by rragu** [eidheim/Simple-WebSocket-Server#31]
We are trying to run the websocket server and the port is getting listened,but we couldn't accept the websocket client connection. We suspect that the callback handler is not working.Can you please assist us on this.                     

Thanks in advance,
Ragu R

**Comment by eidheim** [comment]
What OS are you on, and what is the output of running ws_examples?

**Comment by rragu** [comment]
we are using centOS 6.7 64bit.

**Comment by rragu** [comment]
im using centOS 6.7 64bit

**Comment by boubakerbassem** [comment]
did you check your firewall policy? maybe your system is blocking the connection. did you try to stop your firewall?

**Comment by rragu** [comment]
When we run the ws_examples the port gets listened.

**Comment by eidheim** [comment]
What client are you using?

**Comment by rragu** [comment]
We are using 2 URL's to connect client. Please find below:
chrome-extension://pfdhoblngboilpfeibdedpjgfnlcodoo/index.html
https://www.websocket.org/echo.html

**Comment by eidheim** [comment]
Check the console messages on your browser. I got:
```
The page at 'https://www.websocket.org/echo.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://..../echo?encoding=text'. This request has been blocked; this endpoint must be available over WSS.doConnect @ echo.js:111
echo.js:111 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```

When loading the page with http instead (http://www.websocket.org/echo.html) I got:
```
WebSocket connection to 'ws://....:8080/echo?encoding=text' failed: Connection closed before receiving a handshake response
```

Because of the trailing ?encoding=text I changed the endpoint in ws_examples.cpp to this and it worked:
```c++
auto& echo=server.endpoint["^/echo/?.*$"];
```

**Comment by rragu** [comment]
Great thanks for your help. It works fine now. But can you help us to connect the server with(ws://...:8080) not with(ws://...:8080/echo?encoding=text). Is there any possibilities to run like this?

**Comment by eidheim** [comment]
That depends on the client, and here you are on your own:) Good luck!
