### ISSUE TITLE
MSVC warnings

### ISSUE THREAD

**Issue by MatrixManAtYrService** [eidheim/Simple-WebSocket-Server#33]
As far as I can tell, everything works, so I'm not sure if you care about this--but just in case you do...

Since my project builds with "treat warnings as errors" I had to explicitly ignore the following msvc warnings in order to use your libraries:

Simple-WebSocket-Server

    #pragma warning(disable:4251)
    #pragma warning(disable:4458)
    #pragma warning(disable:4244)
    #include "Simple-WebSocket-Server\server_ws.hpp

Simple-WebSocket-Server (client)

    #pragma warning(disable:4244)
    #include "Simple-WebSocket-Server\client_ws.hpp

Simple-WebServer

    #pragma warning(disable:4503)
    #pragma warning(disable:4101)
    #pragma warning(disable:4458)
    #pragma warning(disable:4457)
    #pragma warning(disable:4244)
    #pragma warning(disable:4251)
    #include "Simple-Web-Server/server_http.hpp

Simple-WebServer (client)

    #pragma warning(disable:4456)
    #pragma warning(disable:4100)
    #pragma warning(disable:4244)
    #include "Simple-Web-Server/client_http.hpp

I tried my hand at fixing them and didn't succeed--but my C++ kung fu is not strong.  If you do want to address these, I'd be happily take another crack at fixing the ones I can and then get you some more information about the ones that I can't.  Just thought you might like to know.

**Comment by eidheim** [comment]
I would not recommend using MSVC (see https://www.reddit.com/r/cpp/comments/4pxmgs/dlib_19_released/ for some resent discussion on this), but I fixed some of the warnings most likely in the commit above.

**Comment by eidheim** [comment]
The remaining warnings are shadowing warnings, and I do not yet have a good solution for that. When I decide on a good solution I will update all of my projects to silence these warnings as well.
