### ISSUE TITLE
Server init message

### ISSUE THREAD

**Issue by krullgra** [eidheim/Simple-WebSocket-Server#37]
I am looking to send a server init message without the client first connecting to the server via web socket. An example might be an http or https request to whos response may include a web socket message from the server.

Something to the effect of:

```
//intent here is to pass in a connection made via different protocol to use for a response back
std::shared_ptr<WsServer::Connection> connection(new WsServer::Connection(new WS(http_session->socket().get_io_service())));

        auto send_stream = std::make_shared<WsServer::SendStream>();
        *send_stream << "cool stuff";
        wsServer.send(connection, send_stream, [](const boost::system::error_code& ec)
        {
            if (ec) {
                std::cout << "Server: Error sending message. " <<
                    "Error: " << ec << ", error message: " << ec.message() << std::endl;
            }
        });
```

Thoughts?

**Comment by eidheim** [comment]
I might be misunderstanding here, but see https://en.wikipedia.org/wiki/WebSocket. The handshake is a HTTP(s) request and you can pass for instance header arguments here that will be available in the connection object. Other than that, I would not try to mix the two protocols (HTTP(S) and WS(S)) further, but try keep them separate. See https://github.com/eidheim/Simple-Web-Server for a similar way of creating HTTP(S) servers in C++.

**Comment by eidheim** [comment]
It is now possible to upgrade a request from Simple-Web-Server to a Connection in Simple-WebSocket-Server. See https://github.com/eidheim/desktop-stream for an example.
