### ISSUE TITLE
Passing connection errors to the onerror() handler?

### ISSUE THREAD

**Issue by classix-do** [eidheim/Simple-WebSocket-Server#50]
Hi,

I have question/change request regarding the error handling in the websocket client.
When I use websocket in JavaScript, and the target host is not available, or not accepting connections, then first the `onerror`-Handler gets called with the connection error and then the `onclose`-Handler gets called.

Currently it's implemented that if the server doesn't respond and the `async_connect()` fails, the exception thrown [here](https://github.com/eidheim/Simple-WebSocket-Server/blob/master/client_ws.hpp#L481) will go up the callstack until it terminates the `io_service.run()` call, and has to be handled by the thread running the `io_service`. This makes it difficult to map the error onto a specific websocket connection and retry to open the connection later.

I would suggest to call `onerror(ec)` & `onclose()` (or only `onerror(ec)`) instead of throwing an exception.
Maybe it's better to generally call `onerror(ec)` instead of throwing the exception.

**Comment by eidheim** [comment]
I have to think some more on this, though my initial thought is that the on-methods should be triggered only after a connection is established. I think it should somehow be possible retry opening the connection if these exceptions are triggered.

**Comment by eidheim** [comment]
Or are you running several clients on one `io_service.run()`?

**Comment by classix-do** [comment]
Exactly. 
I have a bigger application, which starts a _Simple-Web-Server_ to provide dynamic content and opens a long running websocket client connection for data exchange and I wanted them both to share one `io_service`. I also decoupled the Thread, running the `io_service.run()` so that it doesn't know anything about the web server or websocket client, which are using the same `io_service`. 


If `onerror` should only handle errors, which occur during an open connection, then maybe you could make `client.start()` accept a callback function, which only gets called if an error occurred during `connect()`.

**Comment by eidheim** [comment]
Thank you again. I replaced the exception throws with onerror calls.
