### ISSUE TITLE
async-write interleaving

### ISSUE THREAD

**Issue by o0Zz** [eidheim/Simple-WebSocket-Server#57]
Hi,

Fist of all, thanks for your library which is very usefull.

I met below issue with your library :
http://stackoverflow.com/questions/7754695/boost-asio-async-write-how-to-not-interleaving-async-write-calls

And I fix it with below fix:
[async_write_fix.txt](https://github.com/eidheim/Simple-WebSocket-Server/files/711839/async_write_fix.txt)

Feel free to integrate it on your head or re-develop it ;)

BR

**Comment by eidheim** [comment]
Thank you, but this issue has been fixed some time ago. Please use the current master branch or the latest release.
