### ISSUE TITLE
Question about data stream types

### ISSUE THREAD

**Issue by margilc** [eidheim/Simple-WebSocket-Server#60]
Hi,
i've successfully managed to send strings to javascript, but is it also possible, and perhaps more efficient to send integers and floats? I am now sending vectors of doubles as a string stream, but maybe there is a more efficient solution?

**Comment by eidheim** [comment]
It is possible to send binary data. See https://github.com/eidheim/Simple-WebSocket-Server/blob/master/server_ws.hpp#L305.

**Comment by eidheim** [comment]
I do not know how to convert binary data to a float or integer in javascript, but I guess it's possible.
