### ISSUE TITLE
How to use for binary data?

### ISSUE THREAD

**Issue by RichLewis007** [eidheim/Simple-WebSocket-Server#61]
Hi, your Readme says this supports "text/binary frames". How do you send and receive binary data? I don't see any examples in the tests..

thanks!

**Comment by eidheim** [comment]
See https://github.com/eidheim/Simple-WebSocket-Server/blob/master/server_ws.hpp#L305 on which fin_rsv_opcode to use when sending binary data. There are no differences between binary and text data, the difference is on how it is perceived and handled by the receiving end.

**Comment by RichLewis007** [comment]
Thanks! That code comment helped a lot. I was able to send binary data using opcode 130.
