### ISSUE TITLE
It seems that stop() doesn't close the websocket

### ISSUE THREAD

**Issue by Skywalker13** [eidheim/Simple-WebSocket-Server#62]
Hello,

We have a websocket server where the websocket stays alive even after a call on `stop()`. The socket is really closed only when the process is terminated.

Any ideas? It should be like https://github.com/eidheim/Simple-Web-Server/issues/86 ?! no ?!

Thanks

**Comment by eidheim** [comment]
Thank you, I also noticed that stop() is not thread safe here: https://github.com/eidheim/Simple-WebSocket-Server/blob/master/server_ws.hpp#L302. Will look into why the socket is kept alive even after stop() is called.

**Comment by eidheim** [comment]
Let me know if the above commit fixes your use case. Thank you again.

**Comment by Skywalker13** [comment]
Thanks, what about `stop()` on the client side ? https://github.com/eidheim/Simple-WebSocket-Server/blob/master/client_ws.hpp#L191

**Comment by eidheim** [comment]
Sorry for the late response, I realised I had to read up on this a bit. Especially with respect to the Simple-Web-Server project where the client sockets are not stored anywhere, and still a way is needed to close all the sockets when calling stop(). I'll get around to this soon.
