### ISSUE TITLE
Is it possible to receive an incomplete message?

### ISSUE THREAD

**Issue by nikitablack** [eidheim/Simple-WebSocket-Server#67]
I couldn't find the answer in the source code - how does the library handles a big message that didn't fit into one frame? Does it handle it?

**Comment by eidheim** [comment]
Single frame messages can be quite large, but if you would need fragmented messages you would need to play around with the fin_rsv_opcode parameter. See https://github.com/eidheim/Simple-WebSocket-Server/blob/master/server_ws.hpp#L313. Also see https://tools.ietf.org/html/rfc6455#section-5.6.

**Comment by eidheim** [comment]
I would recommend to split up a very large message into smaller "normal" messages if possible though (without using fragmented messages that is).

**Comment by nikitablack** [comment]
Thank you. But I mean something different - is it guaranteed by your library that all messages I receive will be complete? As I understood reading the protocol - if the message is large it can be split into several packets (same as with tcp) and it's the responsibility of the application to make a single message out of multiple parts. And as I understood reading the code there's no such handling. Please correct me if I wrong.

**Comment by eidheim** [comment]
I am not sure if size of a message should determine if the message should be fragmented or not. Usually, single frame messages are sent back and forth, and this library support these no matter how large they are (up to the max length, but practically that will never be a concern).

**Comment by nikitablack** [comment]
I did some tests - I tried to send a very big string from the browser to the localhost server. On the server, I received the same string, so I think my worries are not justified. Thank you for the library.
