### ISSUE TITLE
Incomplete commands in readme - missing "-lpthread"

### ISSUE THREAD

**Issue by Eiji7** [eidheim/Simple-WebSocket-Server#7]
Hi, I just downloaded your code.
Trying to compile ( as in readme ) and got this ( linker ) error:

/usr/bin/ld: /tmp/ccYLDbF9.o: undefined reference to symbol 'pthread_create@@GLIBC_2.1'
/usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Please update your readme by adding: "-lpthread" to your commands.

For example - change line:
`g++ -O3 -std=c++1y ws_examples.cpp -lboost_system -lcrypto -o ws_examples`
to
`g++ -O3 -std=c++1y ws_examples.cpp -lboost_system -lcrypto -o ws_examples -lpthread`

Thanks for your interesting project.
I'm going to use it in future.

**Comment by eidheim** [comment]
It is mentioned that -pthread has to be added on Linux using g++ under Compile and run, but I suggest using cmake and make instead.

**Comment by Eiji7** [comment]
Oh sorry, my mistake
