### ISSUE TITLE
Interop with Simple-Web-Server

### ISSUE THREAD

**Issue by Type1J** [eidheim/Simple-WebSocket-Server#71]
I like your other server library (https://github.com/eidheim/Simple-Web-Server). I haven't tried this library, yet.

I'd really like an example of how to use this library with Simple-Web-Server _on the same port with different endpoints_. It's currently not clear in the readme files if this can even be done, although both readme files do link to the other library.

If this can be done, please add that information to the readme files, and please add an example (to one, both, or a new repo) that shows this being done.

**Comment by eidheim** [comment]
I've done this in a small repository here: https://github.com/eidheim/desktop-stream/blob/master/main.cpp#L182, although it is also described here: https://github.com/eidheim/Simple-WebSocket-Server/blob/master/server_ws.hpp#L377

**Comment by Type1J** [comment]
Thanks! I'll close this issue. I was just looking at desktop-stream as you replied 😄. I had to dig a bit, though. 

I know that I'm closing the issue, but when you have some time, could you please add this comment to the Simple-WebSocket-Server readme ** somewhere? If it looks like it's cluttering the readme, then perhaps a second .md file linked from it. I'm sure that it would either make someone use both libraries that wouldn't otherwise, or save time for someone who uses one, but wants to use them together.

** Linking directly to the lines seems like it would break over time.
