### ISSUE TITLE
Use the wss protocol what the cipher suite in this program

### ISSUE THREAD

**Issue by Wangweilai1** [eidheim/Simple-WebSocket-Server#76]
As the title to say, Use the wss protocol what the cipher suite in this program, I can't find the cipher suite list in this program, I use a certificate is  AES128-GCM-SHA256 arithmetic, But it doesn't work, Can you tell me where the cipher suite list in this program, so that i can create a  suit certificate.
Thanks for you help.

**Comment by eidheim** [comment]
I am pretty sure the cipher suite list is dependent on your OpenSSL installation. On a Unix-like system I would simply write: `openssl ciphers` in a shell.

**Comment by Wangweilai1** [comment]
My OS is Windows, and I want use this program as an Windows Service and client is browser, that is to say ,windows service and browser in one same computer, so I must use self signed certificate,  but I self create a certificate use  AES128-GCM-SHA256 arithmetic, and i found it doesn't work in this program, so it throw myself for a loss, WSS protocol :
`acceptor->async_accept(connection->socket->lowest_layer(), [this, connection](const error_code &ec) {
        //Immediately start accepting a new connection (if io_service hasn't been stopped)
        if(ec != asio::error::operation_aborted)
          accept();

        if(!ec) {
          asio::ip::tcp::no_delay option(true);
          connection->socket->lowest_layer().set_option(option);
          //Set timeout on the following asio::ssl::stream::async_handshake
          auto timer = get_timeout_timer(connection, config.timeout_request);
          connection->socket->async_handshake(asio::ssl::stream_base::server, [this, connection, timer](const error_code &ec) {
            if(timer)
              timer->cancel();
			if (ec)
			{
				using namespace std;
				std::cout << "Error Code: " << ec.value() << std::endl;
				std::cout << "Error Message: "<< ec.message() << std::endl;
				std::cout << "Error Category Name: " << ec.category().name() << std::endl;
			}
            if(!ec)
              read_handshake(connection);
          });`
in async_handshake function the ec always have a error code as follow 
Error Code: 335544539
Error Message: short read
Error Category Name: asio.ssl
I don't know whether IE11 browser prevent connect with this windows server or not, but I already manually added CA certificate into IE11. but it also doesn't work, so can you help me to solve this problem? 
My environment:
OS: windows10， IDE:VS2015, Boost: boost_1_64_0,  openssl: 1.0.2, 

I was sincerely thanks for you help, and looking forward to your reply.

**Comment by Wangweilai1** [comment]
When I use openssl tool to connect to windows server have a error as follow, I don't know what error ?

OpenSSL> s_client -connect 127.0.0.1:90 -CAfile ca.crt
CONNECTED(000001B8)
depth=1 C = CN, ST = BeiJing, L = BeiJing, O = wintone.com.cn, OU = 127.0.0.1, CN = 127.0.0.1, emailAddress = www.wintone.com.cn
verify return:1
depth=0 C = CN, ST = BeiJing, O = wintone.com.cn, OU = 127.0.0.1, CN = 127.0.0.1, emailAddress = www.wintone.com.cn
verify return:1
20664:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:.\ssl\s23_lib.c:177:
---
Certificate chain
 0 s:/C=CN/ST=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
   i:/C=CN/ST=BeiJing/L=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
 1 s:/C=CN/ST=BeiJing/L=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
   i:/C=CN/ST=BeiJing/L=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIEEjCCAvqgAwIBAgIBBTANBgkqhkiG9w0BAQsFADCBlTELMAkGA1UEBhMCQ04x
EDAOBgNVBAgMB0JlaUppbmcxEDAOBgNVBAcMB0JlaUppbmcxFzAVBgNVBAoMDndp
bnRvbmUuY29tLmNuMRIwEAYDVQQLDAkxMjcuMC4wLjExEjAQBgNVBAMMCTEyNy4w
LjAuMTEhMB8GCSqGSIb3DQEJARYSd3d3LndpbnRvbmUuY29tLmNuMCAXDTE3MDcx
NTEzMTQxMloYDzIwNjkwNDEzMTMxNDEyWjCBgzELMAkGA1UEBhMCQ04xEDAOBgNV
BAgMB0JlaUppbmcxFzAVBgNVBAoMDndpbnRvbmUuY29tLmNuMRIwEAYDVQQLDAkx
MjcuMC4wLjExEjAQBgNVBAMMCTEyNy4wLjAuMTEhMB8GCSqGSIb3DQEJARYSd3d3
LndpbnRvbmUuY29tLmNuMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
qXXGBmOO9ZXFlyhFKBg4ur94mSueHQJ8k3JkRhe2K0IPVH+q35TiB78fNjz5E60Q
tBuAj7O368gN3fVdT/ivmo/z17RcyORXm8UHobCGfZZJameg+fIqook+BGZp0ytN
rK+u+MZxvGwFa28zpZYMTZpQ3VS5MJV/Ib2NauSmfQwVD+++XI08tQien/Gb0kC+
7VN6tHDbl4hQg6YoM46PqKrsFj6mDAKNpDnlSDOLiCgXe8pioQkFDIg9it3aXAfd
Fq9UN1IGLKW9MGcryqZl3/sMwn1xXDvvhndFdo4LekMB0IUXIWmpTMvqS2p+112N
or4hZSe0Ma1AOZQMWLI/TQIDAQABo3sweTAJBgNVHRMEAjAAMCwGCWCGSAGG+EIB
DQQfFh1PcGVuU1NMIEdlbmVyYXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUY3jY
Q+2fric0w4ixYUiUOEKhOUkwHwYDVR0jBBgwFoAUz4WNuFGOsPPiVWlGix8G3qi4
O1wwDQYJKoZIhvcNAQELBQADggEBAC4y8PBJV6KE+1AizZEHR9iGoSfbIyG8B7y4
L0qhvohnao2xrOwBLTlc6ANs3llUr8kHmBcsiwJLHLjvho8SVQefYIsMQLX1t62Q
K3n8A4+dSrEpkvOp8boQgXl2rFypzBGfh1QOTv+wHHhGBx6BqXmxh6CRipoGCNnF
59HAL5+EmioUFFaciAqV4QG59aw/Dx+Rxqcx5L48o/bOSfSBNnmTjKeKHNCopwno
fqstk5i9q4xDbs6u1M1wOIEszd8SnN1cwp3RQBQRkP+h6T/fuYB07wFuaPyCCR7P
aOSAkzFp8HKw480QDwet+9w4hn46OTmnXS5ytA8uogwBNb7cslc=
-----END CERTIFICATE-----
subject=/C=CN/ST=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
issuer=/C=CN/ST=BeiJing/L=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
---
SSL handshake has read 2205 bytes and written 330 bytes
---
New, TLSv1/SSLv3, Cipher is AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES128-GCM-SHA256
    Session-ID:
    Session-ID-ctx:
    Master-Key: F7BB967DDE851C1372F886664B2DF5C4E7F2A68D3249F10DE7973D65A76E16C2E2215D5A1714DE1CBE0AE154A2454745
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1500189897
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
error in s_client

**Comment by Wangweilai1** [comment]
When I use openssl tool to connect to windows server have a error as follow, I don't know what error ?

OpenSSL> s_client -connect 127.0.0.1:90 -CAfile ca.crt
CONNECTED(000001B8)
depth=1 C = CN, ST = BeiJing, L = BeiJing, O = wintone.com.cn, OU = 127.0.0.1, CN = 127.0.0.1, emailAddress = www.wintone.com.cn
verify return:1
depth=0 C = CN, ST = BeiJing, O = wintone.com.cn, OU = 127.0.0.1, CN = 127.0.0.1, emailAddress = www.wintone.com.cn
verify return:1
20664:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:.\ssl\s23_lib.c:177:
---
Certificate chain
 0 s:/C=CN/ST=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
   i:/C=CN/ST=BeiJing/L=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
 1 s:/C=CN/ST=BeiJing/L=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
   i:/C=CN/ST=BeiJing/L=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIEEjCCAvqgAwIBAgIBBTANBgkqhkiG9w0BAQsFADCBlTELMAkGA1UEBhMCQ04x
EDAOBgNVBAgMB0JlaUppbmcxEDAOBgNVBAcMB0JlaUppbmcxFzAVBgNVBAoMDndp
bnRvbmUuY29tLmNuMRIwEAYDVQQLDAkxMjcuMC4wLjExEjAQBgNVBAMMCTEyNy4w
LjAuMTEhMB8GCSqGSIb3DQEJARYSd3d3LndpbnRvbmUuY29tLmNuMCAXDTE3MDcx
NTEzMTQxMloYDzIwNjkwNDEzMTMxNDEyWjCBgzELMAkGA1UEBhMCQ04xEDAOBgNV
BAgMB0JlaUppbmcxFzAVBgNVBAoMDndpbnRvbmUuY29tLmNuMRIwEAYDVQQLDAkx
MjcuMC4wLjExEjAQBgNVBAMMCTEyNy4wLjAuMTEhMB8GCSqGSIb3DQEJARYSd3d3
LndpbnRvbmUuY29tLmNuMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
qXXGBmOO9ZXFlyhFKBg4ur94mSueHQJ8k3JkRhe2K0IPVH+q35TiB78fNjz5E60Q
tBuAj7O368gN3fVdT/ivmo/z17RcyORXm8UHobCGfZZJameg+fIqook+BGZp0ytN
rK+u+MZxvGwFa28zpZYMTZpQ3VS5MJV/Ib2NauSmfQwVD+++XI08tQien/Gb0kC+
7VN6tHDbl4hQg6YoM46PqKrsFj6mDAKNpDnlSDOLiCgXe8pioQkFDIg9it3aXAfd
Fq9UN1IGLKW9MGcryqZl3/sMwn1xXDvvhndFdo4LekMB0IUXIWmpTMvqS2p+112N
or4hZSe0Ma1AOZQMWLI/TQIDAQABo3sweTAJBgNVHRMEAjAAMCwGCWCGSAGG+EIB
DQQfFh1PcGVuU1NMIEdlbmVyYXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUY3jY
Q+2fric0w4ixYUiUOEKhOUkwHwYDVR0jBBgwFoAUz4WNuFGOsPPiVWlGix8G3qi4
O1wwDQYJKoZIhvcNAQELBQADggEBAC4y8PBJV6KE+1AizZEHR9iGoSfbIyG8B7y4
L0qhvohnao2xrOwBLTlc6ANs3llUr8kHmBcsiwJLHLjvho8SVQefYIsMQLX1t62Q
K3n8A4+dSrEpkvOp8boQgXl2rFypzBGfh1QOTv+wHHhGBx6BqXmxh6CRipoGCNnF
59HAL5+EmioUFFaciAqV4QG59aw/Dx+Rxqcx5L48o/bOSfSBNnmTjKeKHNCopwno
fqstk5i9q4xDbs6u1M1wOIEszd8SnN1cwp3RQBQRkP+h6T/fuYB07wFuaPyCCR7P
aOSAkzFp8HKw480QDwet+9w4hn46OTmnXS5ytA8uogwBNb7cslc=
-----END CERTIFICATE-----
subject=/C=CN/ST=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
issuer=/C=CN/ST=BeiJing/L=BeiJing/O=wintone.com.cn/OU=127.0.0.1/CN=127.0.0.1/emailAddress=www.wintone.com.cn
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
---
SSL handshake has read 2205 bytes and written 330 bytes
---
New, TLSv1/SSLv3, Cipher is AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES128-GCM-SHA256
    Session-ID:
    Session-ID-ctx:
    Master-Key: F7BB967DDE851C1372F886664B2DF5C4E7F2A68D3249F10DE7973D65A76E16C2E2215D5A1714DE1CBE0AE154A2454745
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1500189897
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
error in s_client

**Comment by Wangweilai1** [comment]
Thank for you help, I already solve this problem, The error is that in the wss_examples.cpp 
WssServer server("server.crt", "server.key"); I changed into WssServer server("server.crt", "server.key", "ca.crt"); so that create this problem, when i delete the "ca.crt", it can connect with browser, I don't know why not add "ca.crt"?, in my opinion it should add ca.crt ,but it's error.
in the end, Thank for you help.
