### ISSUE TITLE
JavaScript test failed

### ISSUE THREAD

**Issue by Eiji7** [eidheim/Simple-WebSocket-Server#8]
After compiling:
g++ -O3 -std=c++1y ws_examples.cpp -lboost_system -lcrypto -o ws_examples -lpthread
just run:
./ws_examples
I create a blank HTML5 page with your code:

&lt;!DOCTYPE html&gt;
&lt;html&gt;
	&lt;head&gt;
		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
		&lt;title&gt;WebSocket Test&lt;/title&gt;
	&lt;/head&gt;
	&lt;body&gt;
		&lt;script&gt;
			window.onload=function(){
				var ws=new WebSocket(&quot;ws://localhost:8080/echo&quot;);
				ws.onmessage=function(evt){console.log(evt.data);};
				ws.send(&quot;test&quot;);
			}
		&lt;/script&gt;
	&lt;/body&gt;
&lt;/html&gt;

Just open this in Firefox 37.0.1 and got:

Connection with ws://localhost:8080/echo was interrupted while the page was loading
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable

Server log:
Server: Opened connection 3062891680
Client: Opened connection
Client: Sending message: "Hello"
Server: Message received: "Hello" from 3062891680
Server: Sending message "Hello" to 3062891680
Client: Message received: "Hello"
Client: Sending close connection
Server: Closed connection 3062891680 with status code 1000
Client: Closed connection with status code 1000
Server: Opened connection 3062892680
Server: Closed connection 3062892680 with status code 1001

**Comment by eidheim** [comment]
ws.send is called before the websocket connection is established. Chrome gives a more understandable error message: Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

**Comment by Eiji7** [comment]
Thanks, for quick response.
This code:

&lt;!DOCTYPE html&gt;
&lt;html&gt;
	&lt;head&gt;
		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
		&lt;title&gt;WebSocket Test&lt;/title&gt;
	&lt;/head&gt;
	&lt;body&gt;
		&lt;script&gt;
			window.onload=function(){
				var ws=new WebSocket(&quot;ws://localhost:8080/echo&quot;);
				ws.onmessage=function(evt){console.log(evt.data);};
				ws.onopen=function(evt){
					ws.send(&quot;test&quot;);
					setTimeout(function(){ws.close();}, 1000);
				}
			}
		&lt;/script&gt;
	&lt;/body&gt;
&lt;/html&gt;

work good.
Thank you again.
