### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by kenkit** [eidheim/Simple-WebSocket-Server#81]
I have a client that connects to a server in a while loop.
Each time the connection fails it should check if an exit flag has been triggered.
However the connection takes too long to close and delays closing the app when exit is called.
How do I create a connection timeout ?

**Comment by eidheim** [comment]
Thank you for reminding me. I have not yet implemented timeouts for the SocketClient, but will do that as soon as I have time.

**Comment by kenkit** [comment]
Wow, hahaha i've been working on a really old v1.3.1 branch.
Seems i'll have to upgrade my source. I still use `client.send(send_stream);`
This library is amazing. Keep up!
I use to as a communication system for my game to transfer object cordinates.
