### ISSUE TITLE
Unable to compile against standalone asio

### ISSUE THREAD

**Issue by jstankowski** [eidheim/Simple-WebSocket-Server#83]
Lib fails to compile when "USE_STANDALONE_ASIO" is defined.

In bot client and server `asio::strand strand` should be replaced by `asio::io_service::strand strand`.

Looking at boost::asio one can find:
> /// (Deprecated: Use boost::asio::io_service::strand.) Typedef for backwards compatibility.
> `typedef boost::asio::io_service::strand strand;`

**Comment by eidheim** [comment]
Thank you! Will fix this later Today.
