### ISSUE TITLE
How to stop the server?

### ISSUE THREAD

**Issue by Athius** [eidheim/Simple-WebSocket-Server#84]
Hello,

I try to stop the server when a client send a special command.
I tried to do this using the stop() method inside the on_command. The server is stopped but I have this error:
libc++abi.dylib: terminating
The program has unexpectedly finished.

Does anyone has the same error?

For information I take the last release (2.0.0.rc2) on Mac OS X 10.12.6 with Apple's clang.

**Comment by eidheim** [comment]
You probably have not joined a thread.

**Comment by Athius** [comment]
Thank you so much! It was this mistake effectively!

**Comment by eidheim** [comment]
Glad to hear!
