### ISSUE TITLE
Openssl wants void* instead of char* in 0x1000115fL

### ISSUE THREAD

**Issue by moonshadow565** [eidheim/Simple-WebSocket-Server#91]
The check for openssl wanting void is too small by 1 number :)
https://github.com/eidheim/Simple-WebSocket-Server/blob/master/crypto.hpp#L72
``OPENSSL_VERSION_NUMBER <= 0x1000114fL`` should be ``OPENSSL_VERSION_NUMBER <= 0x1000115fL``

**Comment by eidheim** [comment]
Thank you for investigating and reporting this!
