### ISSUE TITLE
Integration with Simple-Web-Server

### ISSUE THREAD

**Issue by grigorig** [eidheim/Simple-WebSocket-Server#99]
I'd like to serve both a REST API and a WebSocket service from a single listening socket. That means I have to upgrade to the WebSocket protocol with Simple-Web-Server from specific paths only and then migrate the socket to Simple-WebSocket-Server. It looks like this isn't currently supported/possible.

**Comment by eidheim** [comment]
Please have a look at an example where both HTTP and WS is served on one port here: https://github.com/eidheim/desktop-stream

**Comment by grigorig** [comment]
Thank you. That is much more easy than I expected. No idea why I missed this upgrade functionality in Simple-Web-Server!
